"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""


def solve(n=4000000):
    """Find the sum of all even-valued Fibonacci numbers not exceeding `n`."""
    a, b = 1, 2
    result = 0
    while not b > n:
        if b % 2 == 0:
            result += b
        a, b = b, a+b
    return result

if __name__=='__main__':
    from sys import argv
    print solve()
